import { DurableObject } from "cloudflare:workers";

const encoder = new TextEncoder();
const json = (value, status = 200, headers = {}) => new Response(JSON.stringify(value), { status, headers: { "content-type": "application/json; charset=utf-8", ...headers } });
const cookie = request => Object.fromEntries((request.headers.get("cookie") || "").split(";").map(v => v.trim().split("=")).filter(v => v.length === 2));
const hex = bytes => [...new Uint8Array(bytes)].map(v => v.toString(16).padStart(2, "0")).join("");
const randomHex = size => { const value = new Uint8Array(size); crypto.getRandomValues(value); return hex(value); };
async function passwordHash(password, salt) {
  const key = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveBits"]);
  return hex(await crypto.subtle.deriveBits({ name: "PBKDF2", salt: encoder.encode(salt), iterations: 100000, hash: "SHA-256" }, key, 256));
}

export class IsekaiServer extends DurableObject {
  constructor(ctx, env) {
    super(ctx, env); this.ctx = ctx;
    this.sql = ctx.storage.sql;
    for (const statement of [
      "CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,username TEXT NOT NULL,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,user_json TEXT NOT NULL,updated_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,account_id INTEGER NOT NULL,created_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS super_sessions(token TEXT PRIMARY KEY,created_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,sender_id INTEGER NOT NULL,recipient_id INTEGER NOT NULL,body TEXT NOT NULL,sent_at TEXT NOT NULL,media_type TEXT,media_data TEXT,read_at TEXT)",
      "CREATE TABLE IF NOT EXISTS friendships(user_one INTEGER NOT NULL,user_two INTEGER NOT NULL,created_at TEXT NOT NULL,UNIQUE(user_one,user_two))",
      "CREATE TABLE IF NOT EXISTS friend_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,sender_id INTEGER NOT NULL,recipient_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,UNIQUE(sender_id,recipient_id))"
      ,"CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY AUTOINCREMENT,account_id INTEGER NOT NULL,body TEXT NOT NULL,media_type TEXT,media_data TEXT,created_at TEXT NOT NULL)"
      ,"CREATE TABLE IF NOT EXISTS signals(id INTEGER PRIMARY KEY AUTOINCREMENT,sender_id INTEGER NOT NULL,recipient_id INTEGER NOT NULL,type TEXT NOT NULL,payload_json TEXT NOT NULL,created_at TEXT NOT NULL)"
      ,"CREATE TABLE IF NOT EXISTS post_likes(post_id INTEGER NOT NULL,account_id INTEGER NOT NULL,created_at TEXT NOT NULL,UNIQUE(post_id,account_id))"
      ,"CREATE TABLE IF NOT EXISTS post_comments(id INTEGER PRIMARY KEY AUTOINCREMENT,post_id INTEGER NOT NULL,account_id INTEGER NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL)"
      ,"CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,recipient_id INTEGER NOT NULL,actor_id INTEGER NOT NULL,type TEXT NOT NULL,post_id INTEGER,created_at TEXT NOT NULL,read_at TEXT)"
    ]) this.sql.exec(statement);
    try { this.sql.exec("ALTER TABLE posts ADD COLUMN original_post_id INTEGER"); } catch {}
    const bots=[...this.sql.exec("SELECT id FROM accounts WHERE email LIKE '%@example.com' OR username IN ('TesA','TesB','HttpA','HttpB','TestA','TestB','ChatA','ChatB','Diag User','DiagUser','FinalTest') OR json_extract(user_json,'$.nickname') IN ('TesA','TesB','HttpA','HttpB','TestA','TestB','ChatA','ChatB','Diag User','DiagUser','FinalTest')")].map(row=>row.id);
    for(const id of bots){this.sql.exec("DELETE FROM messages WHERE sender_id=? OR recipient_id=?",id,id);this.sql.exec("DELETE FROM signals WHERE sender_id=? OR recipient_id=?",id,id);this.sql.exec("DELETE FROM post_likes WHERE account_id=? OR post_id IN (SELECT id FROM posts WHERE account_id=?)",id,id);this.sql.exec("DELETE FROM post_comments WHERE account_id=? OR post_id IN (SELECT id FROM posts WHERE account_id=?)",id,id);this.sql.exec("DELETE FROM posts WHERE account_id=?",id);this.sql.exec("DELETE FROM friendships WHERE user_one=? OR user_two=?",id,id);this.sql.exec("DELETE FROM friend_requests WHERE sender_id=? OR recipient_id=?",id,id);this.sql.exec("DELETE FROM sessions WHERE account_id=?",id);this.sql.exec("DELETE FROM accounts WHERE id=?",id);}
  }
  one(query, ...args) { return [...this.sql.exec(query, ...args)][0] || null; }
  all(query, ...args) { return [...this.sql.exec(query, ...args)]; }
  account(request) { const token = cookie(request).isekai_session; return token ? this.one("SELECT a.* FROM sessions s JOIN accounts a ON a.id=s.account_id WHERE s.token=?", token) : null; }
  super(request) { const token=cookie(request).isekai_super; return token ? this.one("SELECT token FROM super_sessions WHERE token=?",token) : null; }
  friends(a, b) { return this.one("SELECT 1 ok FROM friendships WHERE user_one=? AND user_two=?", Math.min(a,b), Math.max(a,b)); }
  sockets() { return this.ctx.getWebSockets(); }
  sendTo(id, value) { let delivered=false;for (const ws of this.sockets()) { const info = ws.deserializeAttachment(); if (info?.accountId === id) try { ws.send(JSON.stringify(value));delivered=true; } catch {} }return delivered; }
  broadcast(value = { type: "presence" }) { for (const ws of this.sockets()) try { ws.send(JSON.stringify(value)); } catch {} }
  notify(recipientId,actorId,type,postId=null){if(recipientId===actorId)return;this.sql.exec("INSERT INTO notifications(recipient_id,actor_id,type,post_id,created_at) VALUES(?,?,?,?,?)",recipientId,actorId,type,postId,new Date().toISOString());this.sendTo(recipientId,{type:"notification"});}
  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname === "/presence" && request.headers.get("upgrade") === "websocket") return this.websocket(request);
    if (!url.pathname.startsWith("/api/")) return json({ error: "Not found" }, 404);
    try { return await this.api(request, url); } catch (error) { console.error(error); return json({ error: "Kesalahan server.", details: String(error?.message || error) }, 500); }
  }
  async api(request, url) {
    const method = request.method, path = url.pathname, value = method === "POST" || method === "DELETE" ? await request.json().catch(() => ({})) : {};
    let user = this.account(request);
    if (method === "POST" && path === "/api/register") {
      const profile = value.user || {}, email = String(profile.email || "").trim().toLowerCase(), username = String(profile.username || "").trim(), password = String(value.password || "");
      if (!username) return json({ ok:false,error:"Nama pengguna wajib diisi." },400);
      if (!/^\S+@\S+\.\S+$/.test(email)) return json({ok:false,error:"Format email tidak valid."},400);
      if (password.length < 6) return json({ok:false,error:"Password minimal 6 karakter."},400);
      if (this.one("SELECT id FROM accounts WHERE email=?",email)) return json({ok:false,error:"Email sudah terdaftar. Silakan login."},409);
      profile.email=email; profile.username=username; const salt=randomHex(16), now=new Date().toISOString(), hash=await passwordHash(password,salt);
      this.sql.exec("INSERT INTO accounts(email,username,password_hash,password_salt,user_json,updated_at) VALUES(?,?,?,?,?,?)",email,username,hash,salt,JSON.stringify(profile),now);
      user=this.one("SELECT * FROM accounts WHERE email=?",email); const token=randomHex(32); this.sql.exec("INSERT INTO sessions VALUES(?,?,?)",token,user.id,now);
      return json({ok:true,user:profile},200,{"set-cookie":`isekai_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000`});
    }
    if (method === "POST" && path === "/api/login") {
      const row=this.one("SELECT * FROM accounts WHERE email=?",String(value.email||"").toLowerCase());
      if (!row || await passwordHash(String(value.password||""),row.password_salt)!==row.password_hash) return json({ok:false,error:"Email atau password salah."},401);
      const token=randomHex(32),now=new Date().toISOString(); this.sql.exec("INSERT INTO sessions VALUES(?,?,?)",token,row.id,now); this.sql.exec("UPDATE accounts SET updated_at=? WHERE id=?",now,row.id);
      return json({ok:true,user:JSON.parse(row.user_json)},200,{"set-cookie":`isekai_session=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000`});
    }
    if(method==="POST"&&path==="/api/superuser/login"){if(String(value.id||"")!=="admin007"||String(value.password||"")!=="admin007")return json({ok:false,error:"ID atau password Super User salah."},401);const token=randomHex(32);this.sql.exec("INSERT INTO super_sessions VALUES(?,?)",token,new Date().toISOString());return json({ok:true},200,{"set-cookie":`isekai_super=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=3600`});}
    if(path.startsWith("/api/superuser/")&&!this.super(request))return json({ok:false,error:"Akses Super User ditolak."},403);
    if(method==="GET"&&path==="/api/superuser/accounts"){return json(this.all("SELECT id,email,username,user_json,updated_at FROM accounts ORDER BY id DESC").map(row=>{const u=JSON.parse(row.user_json);return{id:row.id,email:row.email,username:row.username,nickname:u.nickname||u.username,createdAt:u.createdAt||row.updated_at};}));}
    const adminDelete=path.match(/^\/api\/superuser\/accounts\/(\d+)$/);if(method==="DELETE"&&adminDelete){const id=Number(adminDelete[1]);for(const table of ["messages","signals","post_likes","post_comments","posts","friend_requests","friendships","sessions"]){if(table==="post_likes"||table==="post_comments")this.sql.exec(`DELETE FROM ${table} WHERE account_id=? OR post_id IN (SELECT id FROM posts WHERE account_id=?)`,id,id);else if(table==="posts")this.sql.exec("DELETE FROM posts WHERE account_id=?",id);else if(table==="friendships")this.sql.exec("DELETE FROM friendships WHERE user_one=? OR user_two=?",id,id);else if(table==="friend_requests")this.sql.exec("DELETE FROM friend_requests WHERE sender_id=? OR recipient_id=?",id,id);else if(table==="sessions")this.sql.exec("DELETE FROM sessions WHERE account_id=?",id);else this.sql.exec(`DELETE FROM ${table} WHERE sender_id=? OR recipient_id=?`,id,id);}this.sql.exec("DELETE FROM accounts WHERE id=?",id);this.broadcast();return json({ok:true});}
    if (method === "GET" && path === "/api/session") return json(user ? JSON.parse(user.user_json) : null);
    if (!user) return json({error:"Sesi berakhir."},401);
    if (method === "POST" && path === "/api/save") { this.sql.exec("UPDATE accounts SET username=?,user_json=?,updated_at=? WHERE id=?",value.username,JSON.stringify(value),new Date().toISOString(),user.id); this.broadcast(); return json(true); }
    if (method === "POST" && path === "/api/logout") { const token=cookie(request).isekai_session; this.sql.exec("DELETE FROM sessions WHERE token=?",token); return json(true,200,{"set-cookie":"isekai_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0"}); }
    if (method === "DELETE" && path === "/api/account") { this.sql.exec("DELETE FROM messages WHERE sender_id=? OR recipient_id=?",user.id,user.id); this.sql.exec("DELETE FROM signals WHERE sender_id=? OR recipient_id=?",user.id,user.id); this.sql.exec("DELETE FROM posts WHERE account_id=?",user.id); this.sql.exec("DELETE FROM friend_requests WHERE sender_id=? OR recipient_id=?",user.id,user.id); this.sql.exec("DELETE FROM friendships WHERE user_one=? OR user_two=?",user.id,user.id); this.sql.exec("DELETE FROM sessions WHERE account_id=?",user.id); this.sql.exec("DELETE FROM accounts WHERE id=?",user.id); this.broadcast(); return json(true,200,{"set-cookie":"isekai_session=; Path=/; Max-Age=0"}); }
    if (method === "GET" && path === "/api/users") { const online=new Set(this.sockets().map(ws=>ws.deserializeAttachment()?.accountId)); return json(this.all("SELECT id,user_json,updated_at FROM accounts WHERE id<>?",user.id).map(row=>{ const incoming=this.one("SELECT 1 ok FROM friend_requests WHERE sender_id=? AND recipient_id=? AND status='pending'",row.id,user.id),outgoing=this.one("SELECT 1 ok FROM friend_requests WHERE sender_id=? AND recipient_id=? AND status='pending'",user.id,row.id),unread=this.one("SELECT COUNT(*) count FROM messages WHERE sender_id=? AND recipient_id=? AND read_at IS NULL",row.id,user.id); return {...JSON.parse(row.user_json),lastActive:row.updated_at,online:online.has(row.id),unreadCount:unread?.count||0,friendship:this.friends(user.id,row.id)?"friends":incoming?"incoming":outgoing?"outgoing":"none"}; })); }
    if (method === "POST" && path === "/api/friends/request") { const recipient=this.one("SELECT id FROM accounts WHERE email=?",String(value.email||"").toLowerCase()); if(!recipient||recipient.id===user.id||this.friends(user.id,recipient.id)) return json({ok:false,error:"Permintaan tidak valid."},400); const reverse=this.one("SELECT id FROM friend_requests WHERE sender_id=? AND recipient_id=? AND status='pending'",recipient.id,user.id),now=new Date().toISOString(); if(reverse){this.sql.exec("INSERT OR IGNORE INTO friendships VALUES(?,?,?)",Math.min(user.id,recipient.id),Math.max(user.id,recipient.id),now);this.sql.exec("UPDATE friend_requests SET status='accepted' WHERE id=?",reverse.id);this.broadcast();return json({ok:true,accepted:true});} this.sql.exec("INSERT INTO friend_requests(sender_id,recipient_id,status,created_at) VALUES(?,?,'pending',?) ON CONFLICT(sender_id,recipient_id) DO UPDATE SET status='pending',created_at=excluded.created_at",user.id,recipient.id,now); const p=JSON.parse(user.user_json);this.sendTo(recipient.id,{type:"signal",signalType:"friend-request",senderEmail:user.email,senderName:p.nickname||p.username,payload:{}});this.broadcast();return json({ok:true,accepted:false}); }
    if (method === "POST" && path === "/api/friends/respond") { const sender=this.one("SELECT id FROM accounts WHERE email=?",String(value.email||"").toLowerCase()); const req=sender&&this.one("SELECT id FROM friend_requests WHERE sender_id=? AND recipient_id=? AND status='pending'",sender.id,user.id);if(!req)return json({ok:false,error:"Permintaan tidak ditemukan."},404);if(value.accept)this.sql.exec("INSERT OR IGNORE INTO friendships VALUES(?,?,?)",Math.min(user.id,sender.id),Math.max(user.id,sender.id),new Date().toISOString());this.sql.exec("UPDATE friend_requests SET status=? WHERE id=?",value.accept?"accepted":"rejected",req.id);this.broadcast();return json({ok:true}); }
    if (method === "GET" && path === "/api/messages") { const recipient=this.one("SELECT id FROM accounts WHERE email=?",url.searchParams.get("email"));if(!recipient||!this.friends(user.id,recipient.id))return json({ok:false,error:"Chat hanya tersedia untuk teman."},403);const rows=this.all("SELECT sender_id,body,sent_at,media_type,media_data FROM messages WHERE (sender_id=? AND recipient_id=?) OR (sender_id=? AND recipient_id=?) ORDER BY id",user.id,recipient.id,recipient.id,user.id);this.sql.exec("UPDATE messages SET read_at=? WHERE sender_id=? AND recipient_id=? AND read_at IS NULL",new Date().toISOString(),recipient.id,user.id);return json(rows.map(r=>({from:r.sender_id===user.id?"me":"them",text:r.body,time:r.sent_at,mediaType:r.media_type,media:r.media_data}))); }
    if (method === "POST" && path === "/api/messages") { const recipient=this.one("SELECT id FROM accounts WHERE email=?",String(value.recipientEmail||"").toLowerCase()),message=String(value.body||"").trim(),mediaType=String(value.mediaType||""),mediaData=String(value.mediaData||"");if(!recipient||!this.friends(user.id,recipient.id))return json({ok:false,error:"Tambahkan sebagai teman sebelum mengirim chat."},403);if(!message&&!mediaData)return json({ok:false,error:"Pesan kosong."},400);if(mediaData.length>10000000||(mediaType&&!/^(image|video)\//.test(mediaType)))return json({ok:false,error:"Media tidak valid atau terlalu besar."},400);const now=new Date().toISOString();this.sql.exec("INSERT INTO messages(sender_id,recipient_id,body,sent_at,media_type,media_data) VALUES(?,?,?,?,?,?)",user.id,recipient.id,message,now,mediaType,mediaData);const p=JSON.parse(user.user_json),notice={type:"chat",senderEmail:user.email,senderName:p.nickname||p.username,preview:message||(mediaType.startsWith("video/")?"Mengirim video":"Mengirim foto"),mediaType};if(!this.sendTo(recipient.id,notice))this.sql.exec("INSERT INTO signals(sender_id,recipient_id,type,payload_json,created_at) VALUES(?,?,?,?,?)",user.id,recipient.id,"chat",JSON.stringify(notice),now);return json({ok:true}); }
    if (method === "POST" && path === "/api/posts") { const message=String(value.body||"").trim(),mediaType=String(value.mediaType||""),mediaData=String(value.mediaData||"");if(!message&&!mediaData)return json({ok:false,error:"Status kosong."},400);if(mediaData.length>10000000||(mediaType&&!/^(image|video)\//.test(mediaType)))return json({ok:false,error:"Media tidak valid atau terlalu besar."},400);this.sql.exec("INSERT INTO posts(account_id,body,media_type,media_data,created_at) VALUES(?,?,?,?,?)",user.id,message,mediaType,mediaData,new Date().toISOString());const postId=this.one("SELECT last_insert_rowid() id").id;for(const friend of this.all("SELECT CASE WHEN user_one=? THEN user_two ELSE user_one END id FROM friendships WHERE user_one=? OR user_two=?",user.id,user.id,user.id))this.notify(friend.id,user.id,"friend-post",postId);this.broadcast({type:"feed"});return json({ok:true}); }
    if (method === "GET" && path === "/api/posts") { const limit=Math.min(10,Math.max(1,Number(url.searchParams.get("limit"))||10)),offset=Math.max(0,Number(url.searchParams.get("offset"))||0);const rows=this.all(`SELECT p.id,p.account_id,p.body,p.media_type,p.media_data,p.created_at,p.original_post_id,a.user_json,oa.user_json original_user_json,CASE WHEN f.user_one IS NOT NULL THEN 1 ELSE 0 END friend_priority,(SELECT COUNT(*) FROM post_likes l WHERE l.post_id=p.id) like_count,(SELECT COUNT(*) FROM post_likes l WHERE l.post_id=p.id AND l.account_id=?) liked FROM posts p JOIN accounts a ON a.id=p.account_id LEFT JOIN posts op ON op.id=p.original_post_id LEFT JOIN accounts oa ON oa.id=op.account_id LEFT JOIN friendships f ON f.user_one=MIN(?,p.account_id) AND f.user_two=MAX(?,p.account_id) ORDER BY friend_priority DESC,p.created_at DESC LIMIT ? OFFSET ?`,user.id,user.id,user.id,limit+1,offset);return json({posts:rows.slice(0,limit).map(row=>{const profile=JSON.parse(row.user_json),comments=this.all("SELECT c.id,c.body,c.created_at,a.user_json FROM post_comments c JOIN accounts a ON a.id=c.account_id WHERE c.post_id=? ORDER BY c.created_at",row.id).map(c=>{const author=JSON.parse(c.user_json);return{id:c.id,author:author.nickname||author.username,avatar:author.photo||"",text:c.body,createdAt:c.created_at};});return{id:row.id,author:profile.nickname||profile.username,avatar:profile.photo||"",job:profile.job||"",level:profile.level||1,text:row.body,mediaType:row.media_type,media:row.media_data,createdAt:row.created_at,isFriend:Boolean(row.friend_priority),isOwner:row.account_id===user.id,likeCount:Number(row.like_count)||0,liked:Boolean(row.liked),comments,sharedFrom:row.original_user_json?(JSON.parse(row.original_user_json).nickname||JSON.parse(row.original_user_json).username):""};}),hasMore:rows.length>limit}); }
    const likeMatch=path.match(/^\/api\/posts\/(\d+)\/like$/);if(method==="POST"&&likeMatch){const postId=Number(likeMatch[1]),post=this.one("SELECT id,account_id FROM posts WHERE id=?",postId);if(!post)return json({ok:false,error:"Status tidak ditemukan."},404);if(this.one("SELECT 1 ok FROM post_likes WHERE post_id=? AND account_id=?",postId,user.id))this.sql.exec("DELETE FROM post_likes WHERE post_id=? AND account_id=?",postId,user.id);else{this.sql.exec("INSERT INTO post_likes VALUES(?,?,?)",postId,user.id,new Date().toISOString());this.notify(post.account_id,user.id,"like",postId);}this.broadcast({type:"feed"});return json({ok:true});}
    const commentMatch=path.match(/^\/api\/posts\/(\d+)\/comments$/);if(method==="POST"&&commentMatch){const postId=Number(commentMatch[1]),comment=String(value.body||"").trim(),post=this.one("SELECT id,account_id FROM posts WHERE id=?",postId);if(!comment)return json({ok:false,error:"Komentar kosong."},400);if(!post)return json({ok:false,error:"Status tidak ditemukan."},404);this.sql.exec("INSERT INTO post_comments(post_id,account_id,body,created_at) VALUES(?,?,?,?)",postId,user.id,comment,new Date().toISOString());this.notify(post.account_id,user.id,"comment",postId);this.broadcast({type:"feed"});return json({ok:true});}
    const shareMatch=path.match(/^\/api\/posts\/(\d+)\/share$/);if(method==="POST"&&shareMatch){const original=this.one("SELECT * FROM posts WHERE id=?",Number(shareMatch[1]));if(!original)return json({ok:false,error:"Status tidak ditemukan."},404);this.sql.exec("INSERT INTO posts(account_id,body,media_type,media_data,created_at,original_post_id) VALUES(?,?,?,?,?,?)",user.id,original.body,original.media_type,original.media_data,new Date().toISOString(),original.id);this.notify(original.account_id,user.id,"share",original.id);this.broadcast({type:"feed"});return json({ok:true});}
    const deletePostMatch=path.match(/^\/api\/posts\/(\d+)$/);if(method==="DELETE"&&deletePostMatch){const postId=Number(deletePostMatch[1]),post=this.one("SELECT account_id FROM posts WHERE id=?",postId);if(!post)return json({ok:false,error:"Status tidak ditemukan."},404);if(post.account_id!==user.id)return json({ok:false,error:"Kamu hanya dapat menghapus status sendiri."},403);this.sql.exec("DELETE FROM post_likes WHERE post_id=?",postId);this.sql.exec("DELETE FROM post_comments WHERE post_id=?",postId);this.sql.exec("DELETE FROM notifications WHERE post_id=?",postId);this.sql.exec("DELETE FROM posts WHERE id=?",postId);this.broadcast({type:"feed"});return json({ok:true});}
    if(method==="GET"&&path==="/api/notifications"){const rows=this.all("SELECT n.id,n.type,n.post_id,n.created_at,n.read_at,a.user_json FROM notifications n JOIN accounts a ON a.id=n.actor_id WHERE n.recipient_id=? ORDER BY n.id DESC LIMIT 50",user.id);return json(rows.map(row=>{const actor=JSON.parse(row.user_json);return{id:row.id,type:row.type,postId:row.post_id,actor:actor.nickname||actor.username,avatar:actor.photo||"",createdAt:row.created_at,read:Boolean(row.read_at)};}));}
    if(method==="POST"&&path==="/api/notifications/read"){this.sql.exec("UPDATE notifications SET read_at=? WHERE recipient_id=? AND read_at IS NULL",new Date().toISOString(),user.id);return json({ok:true});}
    if (method === "POST" && path === "/api/signals") { const recipient=this.one("SELECT id FROM accounts WHERE email=?",String(value.recipientEmail||"").toLowerCase()),type=String(value.type||"");if(!recipient||!["party-invite","party-response","call-offer","call-answer","call-ice","call-end"].includes(type))return json({ok:false,error:"Signal tidak valid."},400);this.sql.exec("INSERT INTO signals(sender_id,recipient_id,type,payload_json,created_at) VALUES(?,?,?,?,?)",user.id,recipient.id,type,JSON.stringify(value.payload||{}),new Date().toISOString());return json({ok:true}); }
    if (method === "GET" && path === "/api/signals") { const after=Math.max(0,Number(url.searchParams.get("after"))||0),rows=this.all("SELECT s.id,s.type,s.payload_json,a.email,a.user_json FROM signals s JOIN accounts a ON a.id=s.sender_id WHERE s.recipient_id=? AND s.id>? ORDER BY s.id LIMIT 100",user.id,after);return json(rows.map(row=>{const profile=JSON.parse(row.user_json),payload=JSON.parse(row.payload_json||"{}");return row.type==="chat"?{id:row.id,...payload}:{id:row.id,type:"signal",signalType:row.type,senderEmail:row.email,senderName:profile.nickname||profile.username,payload};})); }
    return json({error:"API tidak ditemukan"},404);
  }
  websocket(request) { const user=this.account(request);if(!user)return new Response("Unauthorized",{status:401});const pair=new WebSocketPair(),client=pair[0],server=pair[1];server.serializeAttachment({accountId:user.id,email:user.email});this.ctx.acceptWebSocket(server,[`account:${user.id}`]);server.send(JSON.stringify({type:"ready"}));this.broadcast();return new Response(null,{status:101,webSocket:client}); }
  webSocketMessage(ws, raw) { try { const message=JSON.parse(String(raw)),info=ws.deserializeAttachment();if(!["party-invite","party-response","call-offer","call-answer","call-ice","call-end"].includes(message.type))return;const user=this.one("SELECT * FROM accounts WHERE id=?",info.accountId),recipient=this.one("SELECT id FROM accounts WHERE email=?",String(message.recipientEmail||"").toLowerCase());if(!user||!recipient)return;const p=JSON.parse(user.user_json);this.sendTo(recipient.id,{type:"signal",signalType:message.type,senderEmail:user.email,senderName:p.nickname||p.username,payload:message.payload||{}});}catch{} }
  webSocketClose() { this.broadcast(); }
  webSocketError() { this.broadcast(); }
}

export default {
  async fetch(request, env) {
    const url=new URL(request.url);
    if(url.pathname.startsWith("/api/")||url.pathname==="/presence") return env.ISEKAI.getByName("global").fetch(request);
    return env.ASSETS.fetch(request);
  }
};
